export * as logger from 'https://deno.land/std@0.74.0/log/mod.ts';
export { parse } from 'https://deno.land/std@0.74.0/flags/mod.ts';
export {
  red,
  green,
  bold,
  dim,
  italic,
  underline,
  inverse,
  hidden,
  strikethrough,
  black,
  yellow,
  blue,
  magenta,
  cyan,
  white,
  gray,
  bgBlack,
  bgRed,
  bgGreen,
  bgYellow,
  bgBlue,
  bgMagenta,
  bgCyan,
  bgWhite,
} from "https://deno.land/std@0.74.0/fmt/colors.ts";